### ISSUE TITLE
Failed to compile?

### ISSUE THREAD

**Issue by NeonSupernova** [Tee1er/boing#5]
- OS Ubuntu 20.04
- npm 16.14.4
- node 10.19.0
- java 17.0.1

Don't use js much so I don't really know what happening here, error nonetheless:
![image](https://user-images.githubusercontent.com/78397254/147030799-8432094d-ca7c-49ad-9a1e-4320b5d3217d.png)

**Comment by Tee1er** [comment]
Seems like a Discord.js issue.

I don't use Ubuntu much so I might have to spin up a VM for this ... @NifleySnifley 's testing on Linux seemed to work fine, but something could've changed in the time since.

**Comment by NifleySnifley** [comment]
It appears that your node version isn't supported, node versions 16+ should run boing fine. Older node versions sometimes might not support the new JavaScript features some libraries use.

**Comment by NeonSupernova** [comment]
Updated to to a newer node, and edited the shell script to use it, but still getting an error:
![image](https://user-images.githubusercontent.com/78397254/147127005-2c7bd557-03ac-44e6-9919-25c4d93929e1.jpeg)
![image](https://user-images.githubusercontent.com/78397254/147127020-677b8aca-4d32-4fe7-a2ee-edd2bd652187.png)

**Comment by NeonSupernova** [comment]
On inspection, It seems an install of npm install nodejs 10 by default, and won't use the snap package installed.
@NifleySnifley How do you have your npm configured to use node 16+?

**Comment by Tee1er** [comment]
> On inspection, It seems an install of npm install nodejs 10 by default, and won't use the snap package installed.

NPM should come installed with Node.js, not the other way around ... how did you install Node on your machine?

**Comment by NeonSupernova** [comment]
I installed npm from apt, which installed nodejs 10.

**Comment by Tee1er** [comment]
Oh, that could be why

Can you try installing from somewhere else that'll allow you to get v16?

**Comment by NeonSupernova** [comment]
I already did thanks! I got it working. You may want to make the shell script a bit more intuitive. Perhaps check versions installed or whether npm, node, and java are installed at all. I got to work by installing 'n' and upgraded my node version.
