### ISSUE TITLE
Yay, more issues

### ISSUE THREAD

**Issue by NeonSupernova** [Tee1er/boing#6]
![image](https://user-images.githubusercontent.com/78397254/147135279-7146853b-9dd3-4f68-a31d-9044dcece15a.png)
What's the problem here?

**Comment by NifleySnifley** [comment]
Double check your token, and the permissions of the bot you created.
The README has some instructions on setting up the bot (Im assuming youve read it already).
Make sure the bot's permissions allow it to send messages (and read the channel). You could also double check your network connection, the discord library seems to be having issues sending web requests.

**Comment by Tee1er** [comment]
What command caused this error?

(or, what did you do to cause this error?)

But, yeah, looks like a token issue.

**Comment by Tee1er** [comment]
RET2NzgxMzU0NzUzJRKyMjIy.YG81Yp.3rXqDe7oY6PxicCFeW-KqpJDPuQ

Token should look like that (not actual token, randomly generated)

Make sure you've entered in the right one, like Nifley said

**Comment by Tee1er** [comment]
Any update on this issue?

**Comment by NeonSupernova** [comment]
No, this still doesn't work, and I made sure I had adequate bot perms, as well as the token. Sorry for the late response btw

**Comment by Tee1er** [comment]
It's okay

Both me and @NifleySnifley have tested on Linux and it's been working fine. I've been looking at a couple Discord.js bug reports and it seems to be more so an issue with that library; does this only happen occasionally and is there a specific action that triggers it? It's a bit hard to reproduce right now w/ the information we have

**Comment by NeonSupernova** [comment]
I have an issue every time I attempt to run it.

**Comment by Tee1er** [comment]
It's been a really long time, sorry :/

I did make a new [guide ](https://github.com/Tee1er/boing/blob/main/docs/linux-install.md)for Linux systems in case that's useful, though. 

It should hopefully clarify a couple things.
